extends Node

enum WeaponType {shotgun, sword, NOVA}

enum ENEMY_TYPE {SLOW, MEDIUM, FAST}
enum WEAPON_STATS {DAM, RANGE, PELLET_COUNT, ACCURACY, ATTACK_SPEED, SPEED}
enum ENT_STATS {HEALTH, MOVE_SPEED, SHIELD}
